#!/bin/env python
# Copyright 2013 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
import plistlib
import pprint
import sys

from binplist import binplist


if __name__ == "__main__":
  if len(sys.argv) <= 1:
    print "Usage: %s <file>" % sys.argv[0]
    sys.exit(-1)

  with open(sys.argv[1]) as fd:
    plist = binplist.BinaryPlist(file_obj=fd)
    try:
      res = plist.Parse()
      if plist.is_corrupt:
        logging.warn("%s LOOKS CORRUPTED. You might not obtain all data!\n",
                     sys.argv[1])
      pprint.PrettyPrinter().pprint(res)
    except binplist.FormatError, e:
      pprint.PrettyPrinter().pprint(plistlib.readPlist(sys.argv[1]))
